export default {
    icCurLoc: require('../../assets/image/Oval.png'),
    icGreenMarker: require("../../assets/image/greenMarker.png"),
    greenIndicator: require("../../assets/image/greenIndicator.png"),
    icBike: require("../../assets/image/bike.png"),
    running: require("../../assets/image/running_human.png"),
    close: require("../../assets/image/cancel_52px.png"),
    map: require("../../assets/image/google_maps_old_96px.png"),
    closeWhite: require("../../assets/image/closeWhite_60px.png"),
    help: require("../../assets/image/ask_question_48px.png"),
    alarmClock: require("../../assets/image/alarm_clock_24px.png"),
    speed: require("../../assets/image/speed_24px.png"),
    backWhiteCircle: require("../../assets/image/back_to_48px.png"),
    running_white: require("../../assets/image/running_52px.png"),
    energy : require("../../assets/image/energy_50px.png"),
    wallet: require("../../assets/image/wallet_26px.png"),
    coin: require("../../assets/image/coin_30px.png"),
    sneakers: require("../../assets/image/sneakers_100px.png"),
    back: require("../../assets/image/back_24px.png"),
    runningWhite: require("../../assets/image/runningWhite_52px.png"),
    sneakersWhite: require("../../assets/image/sneakersWhite_100px.png")
}